project:
  type: website
  output-dir: docs

website:
  title: "Learn to Visualize with Me!"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: journal
    css: styles.css



